<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class CompanySeeder extends Seeder
{
    public function run()
    {
        $companies = [
            [
                'id' => 1,
                'name' => 'HR Management System',
                'registration_number' => 'REG-2023-HR001',
                'tax_identification_number' => 'TIN-101234567',
                'sector' => 'technology',
                'risk_level' => 'low',
                'address' => 'Dar es Salaam, Tanzania',
                'city' => 'Dar es Salaam',
                'region' => 'Dar es Salaam',
                'postal_code' => '11101',
                'phone' => '+255 22 123 4567',
                'email' => 'info@hrsystem.co.tz',
                'website' => 'https://hrsystem.co.tz',
                'union_status' => 'non_unionized',
                'union_name' => null,
                'collective_agreement' => null,
                'employee_count' => 156,
                'registration_date' => '2023-01-15',
                'is_active' => true,
                'compliance_settings' => json_encode(['elra_compliance' => true, 'osha_compliance' => true]),
                'labor_law_settings' => json_encode(['minimum_wage' => true, 'working_hours' => '8h/day']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'Tanzania Cigarette Company (TCC)',
                'registration_number' => 'REG-1998-TCC001',
                'tax_identification_number' => 'TIN-102345678',
                'sector' => 'manufacturing',
                'risk_level' => 'medium',
                'address' => 'Industrial Area, Dar es Salaam',
                'city' => 'Dar es Salaam',
                'region' => 'Dar es Salaam',
                'postal_code' => '11102',
                'phone' => '+255 22 211 1234',
                'email' => 'info@tcc.co.tz',
                'website' => 'https://tcc.co.tz',
                'union_status' => 'unionized',
                'union_name' => 'TCC Workers Union',
                'collective_agreement' => 'TCC-CA-2023',
                'employee_count' => 1200,
                'registration_date' => '1998-05-20',
                'is_active' => true,
                'compliance_settings' => json_encode(['elra_compliance' => true, 'osha_compliance' => true]),
                'labor_law_settings' => json_encode(['minimum_wage' => true, 'working_hours' => '8h/day']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'Tanzania Breweries Limited (TBL)',
                'registration_number' => 'REG-1990-TBL001',
                'tax_identification_number' => 'TIN-103456789',
                'sector' => 'manufacturing',
                'risk_level' => 'medium',
                'address' => 'Mikocheni, Dar es Salaam',
                'city' => 'Dar es Salaam',
                'region' => 'Dar es Salaam',
                'postal_code' => '11103',
                'phone' => '+255 22 213 5678',
                'email' => 'info@tbl.co.tz',
                'website' => 'https://tbl.co.tz',
                'union_status' => 'unionized',
                'union_name' => 'Brewery Workers Union',
                'collective_agreement' => 'TBL-CA-2023',
                'employee_count' => 850,
                'registration_date' => '1990-03-10',
                'is_active' => true,
                'compliance_settings' => json_encode(['elra_compliance' => true, 'osha_compliance' => true]),
                'labor_law_settings' => json_encode(['minimum_wage' => true, 'working_hours' => '8h/day']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'NMB Bank Plc',
                'registration_number' => 'REG-1997-NMB001',
                'tax_identification_number' => 'TIN-104567890',
                'sector' => 'services',
                'risk_level' => 'low',
                'address' => 'Ohio Street, Dar es Salaam',
                'city' => 'Dar es Salaam',
                'region' => 'Dar es Salaam',
                'postal_code' => '11104',
                'phone' => '+255 22 111 1234',
                'email' => 'info@nmbbank.co.tz',
                'website' => 'https://nmbbank.co.tz',
                'union_status' => 'unionized',
                'union_name' => 'Banking Workers Union',
                'collective_agreement' => 'NMB-CA-2023',
                'employee_count' => 3200,
                'registration_date' => '1997-08-15',
                'is_active' => true,
                'compliance_settings' => json_encode(['elra_compliance' => true, 'osha_compliance' => true]),
                'labor_law_settings' => json_encode(['minimum_wage' => true, 'working_hours' => '8h/day']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'CRDB Bank Plc',
                'registration_number' => 'REG-1995-CRDB001',
                'tax_identification_number' => 'TIN-105678901',
                'sector' => 'services',
                'risk_level' => 'low',
                'address' => 'Kaweya Street, Dar es Salaam',
                'city' => 'Dar es Salaam',
                'region' => 'Dar es Salaam',
                'postal_code' => '11105',
                'phone' => '+255 22 212 3456',
                'email' => 'info@crdbbank.co.tz',
                'website' => 'https://crdbbank.co.tz',
                'union_status' => 'unionized',
                'union_name' => 'Banking Workers Union',
                'collective_agreement' => 'CRDB-CA-2023',
                'employee_count' => 2800,
                'registration_date' => '1995-12-01',
                'is_active' => true,
                'compliance_settings' => json_encode(['elra_compliance' => true, 'osha_compliance' => true]),
                'labor_law_settings' => json_encode(['minimum_wage' => true, 'working_hours' => '8h/day']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'name' => 'Tigo Tanzania',
                'registration_number' => 'REG-1994-TIGO001',
                'tax_identification_number' => 'TIN-106789012',
                'sector' => 'technology',
                'risk_level' => 'medium',
                'address' => 'Mikocheni B, Dar es Salaam',
                'city' => 'Dar es Salaam',
                'region' => 'Dar es Salaam',
                'postal_code' => '11106',
                'phone' => '+255 22 214 7890',
                'email' => 'info@tigo.co.tz',
                'website' => 'https://tigo.co.tz',
                'union_status' => 'non_unionized',
                'union_name' => null,
                'collective_agreement' => null,
                'employee_count' => 650,
                'registration_date' => '1994-06-20',
                'is_active' => true,
                'compliance_settings' => json_encode(['elra_compliance' => true, 'osha_compliance' => true]),
                'labor_law_settings' => json_encode(['minimum_wage' => true, 'working_hours' => '8h/day']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'name' => 'Vodacom Tanzania',
                'registration_number' => 'REG-1999-VOD001',
                'tax_identification_number' => 'TIN-107890123',
                'sector' => 'technology',
                'risk_level' => 'medium',
                'address' => 'Mlimani City, Dar es Salaam',
                'city' => 'Dar es Salaam',
                'region' => 'Dar es Salaam',
                'postal_code' => '11107',
                'phone' => '+255 22 215 8901',
                'email' => 'info@vodacom.co.tz',
                'website' => 'https://vodacom.co.tz',
                'union_status' => 'non_unionized',
                'union_name' => null,
                'collective_agreement' => null,
                'employee_count' => 750,
                'registration_date' => '1999-09-10',
                'is_active' => true,
                'compliance_settings' => json_encode(['elra_compliance' => true, 'osha_compliance' => true]),
                'labor_law_settings' => json_encode(['minimum_wage' => true, 'working_hours' => '8h/day']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'name' => 'Airtel Tanzania',
                'registration_number' => 'REG-2001-AIR001',
                'tax_identification_number' => 'TIN-108901234',
                'sector' => 'technology',
                'risk_level' => 'medium',
                'address' => 'Samora Avenue, Dar es Salaam',
                'city' => 'Dar es Salaam',
                'region' => 'Dar es Salaam',
                'postal_code' => '11108',
                'phone' => '+255 22 216 9012',
                'email' => 'info@airtel.co.tz',
                'website' => 'https://airtel.co.tz',
                'union_status' => 'non_unionized',
                'union_name' => null,
                'collective_agreement' => null,
                'employee_count' => 580,
                'registration_date' => '2001-03-15',
                'is_active' => true,
                'compliance_settings' => json_encode(['elra_compliance' => true, 'osha_compliance' => true]),
                'labor_law_settings' => json_encode(['minimum_wage' => true, 'working_hours' => '8h/day']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'name' => 'TANESCO',
                'registration_number' => 'REG-1964-TAN001',
                'tax_identification_number' => 'TIN-109012345',
                'sector' => 'government',
                'risk_level' => 'high',
                'address' => 'Ubungo, Dar es Salaam',
                'city' => 'Dar es Salaam',
                'region' => 'Dar es Salaam',
                'postal_code' => '11109',
                'phone' => '+255 22 217 0123',
                'email' => 'info@tanesco.co.tz',
                'website' => 'https://tanesco.co.tz',
                'union_status' => 'unionized',
                'union_name' => 'Energy Workers Union',
                'collective_agreement' => 'TANESCO-CA-2023',
                'employee_count' => 4500,
                'registration_date' => '1964-01-01',
                'is_active' => true,
                'compliance_settings' => json_encode(['elra_compliance' => true, 'osha_compliance' => true]),
                'labor_law_settings' => json_encode(['minimum_wage' => true, 'working_hours' => '8h/day']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'name' => 'Twiga Cement',
                'registration_number' => 'REG-1980-TWI001',
                'tax_identification_number' => 'TIN-110123456',
                'sector' => 'manufacturing',
                'risk_level' => 'high',
                'address' => 'Mbeya, Tanzania',
                'city' => 'Mbeya',
                'region' => 'Mbeya',
                'postal_code' => '53101',
                'phone' => '+255 25 250 1234',
                'email' => 'info@twigacement.co.tz',
                'website' => 'https://twigacement.co.tz',
                'union_status' => 'unionized',
                'union_name' => 'Manufacturing Workers Union',
                'collective_agreement' => 'TWIGA-CA-2023',
                'employee_count' => 320,
                'registration_date' => '1980-07-15',
                'is_active' => true,
                'compliance_settings' => json_encode(['elra_compliance' => true, 'osha_compliance' => true]),
                'labor_law_settings' => json_encode(['minimum_wage' => true, 'working_hours' => '8h/day']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'name' => 'Azam Tanzania',
                'registration_number' => 'REG-1967-AZA001',
                'tax_identification_number' => 'TIN-111234567',
                'sector' => 'manufacturing',
                'risk_level' => 'medium',
                'address' => 'Chang\'ombe, Dar es Salaam',
                'city' => 'Dar es Salaam',
                'region' => 'Dar es Salaam',
                'postal_code' => '11110',
                'phone' => '+255 22 218 1234',
                'email' => 'info@azam.co.tz',
                'website' => 'https://azam.co.tz',
                'union_status' => 'unionized',
                'union_name' => 'Food Processing Workers Union',
                'collective_agreement' => 'AZAM-CA-2023',
                'employee_count' => 2100,
                'registration_date' => '1967-04-20',
                'is_active' => true,
                'compliance_settings' => json_encode(['elra_compliance' => true, 'osha_compliance' => true]),
                'labor_law_settings' => json_encode(['minimum_wage' => true, 'working_hours' => '8h/day']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'name' => 'Yara Tanzania',
                'registration_number' => 'REG-2005-YAR001',
                'tax_identification_number' => 'TIN-112345678',
                'sector' => 'agriculture',
                'risk_level' => 'medium',
                'address' => 'Dar es Salaam, Tanzania',
                'city' => 'Dar es Salaam',
                'region' => 'Dar es Salaam',
                'postal_code' => '11111',
                'phone' => '+255 22 219 2345',
                'email' => 'info@yara.co.tz',
                'website' => 'https://yara.co.tz',
                'union_status' => 'non_unionized',
                'union_name' => null,
                'collective_agreement' => null,
                'employee_count' => 180,
                'registration_date' => '2005-11-10',
                'is_active' => true,
                'compliance_settings' => json_encode(['elra_compliance' => true, 'osha_compliance' => true]),
                'labor_law_settings' => json_encode(['minimum_wage' => true, 'working_hours' => '8h/day']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('companies')->insert($companies);
    }
}
